name: "Setup environment"
description: "Setup the environment for the project"
runs:
  using: "composite"
  steps:
    - name: Git submodules init
      run: git submodule init
      shell: bash

    - name: Git submodules update
      run: git submodule update
      shell: bash

    - name: Install Node.js ⚙️
      uses: actions/setup-node@v4
      with:
        node-version-file: ".nvmrc"

    - name: Get Yarn Cache Directory Path
      id: yarn-cache-dir-path
      run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT
      shell: bash

    - name: Restore Dependencies Cache
      uses: actions/cache/restore@v3
      id: restore-cache
      with:
        path: |
          node_modules
          ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-${{ hashFiles('yarn.lock') }}
        restore-keys: ${{ runner.os }}-

    - name: Install Dependencies
      run: yarn
      shell: bash

    - name: Cache Dependencies
      uses: actions/cache/save@v3
      if: steps.restore-cache.outputs.cache-hit != 'true'
      with:
        path: |
          node_modules
          ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-${{ hashFiles('yarn.lock') }}
